spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: produtos
              uri: lb://PRODUTOS-SERVICE
              predicates:
                - Path=/produtos/**
              filters:
                # - StripPrefix=1

            - id: pedidos
              uri: lb://PEDIDOS-SERVICE
              predicates:
                - Path=/pedidos/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8700
